### ISSUE TITLE
Allow additional customization options for fields

### ISSUE THREAD

**Issue by TEvans00** [eleviven/react-native-alertbox#2]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

While using this alertbox (which works very nicely!), I wanted to make it so that one of the fields did not autocapitalize the first letter and also hid the text. However, I was not able to perform this level of customization with the way the code is currently written.  I was able to make a small change to the package that allowed me to make the changes I needed, and I think it would be neat if these and other customization options were included in the package.

Here are the changes that solved my problem:

```diff
diff --git a/node_modules/react-native-alertbox/src/alertbox.js b/node_modules/react-native-alertbox/src/alertbox.js
index 6910047..e142136 100644
--- a/node_modules/react-native-alertbox/src/alertbox.js
+++ b/node_modules/react-native-alertbox/src/alertbox.js
@@ -75,6 +75,8 @@ export default function Alertbox({
                     <TextInput
                       name={field.name}
                       placeholder={field.placeholder}
+                      autoCapitalize={field.autoCapitalize}
+                      secureTextEntry={field.secureTextEntry}
                       onChangeText={(text) =>
                         setFieldState((prevState) => ({
                           ...prevState,
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by firuzcanh** [comment]
@TEvans00 Thank you for feedback. It's great to get feedback like that. I haven't updated this for a long time. It's great chance to update it. I will try to make TextInput more functional this weekend.

**Comment by firuzcanh** [comment]
I have published new version. You can pass all input props to fields now. I have also added dark mode support.

 If you see any improvements you can share with me any time.

**Comment by TEvans00** [comment]
Thank you for working on this! I just upgraded to the new version this morning to test it out and it works great!
